#!/bin/sh

main() {
    parse_opts "$@"

    { [ -n "$help" ] && help; } ||
    { [ -n "$icon" ] && icon; } ||
    { [ -n "$number" ] && number; } ||
    { [ -n "$clear" ] && cache; } ||
    { icon; }
}

cache() {
    { [ -f ~/.cache/dmoji/emojis.txt ] && rm -f ~/.cache/dmoji/emojis.txt; } ||
    { echo "There is no cache to clear."; }
}

cmd() {
    [ ! -d ~/.cache/dmoji ] && mkdir -p ~/.cache/dmoji
    [ ! -f ~/.cache/dmoji/emojis.txt ] && wget -O ~/.cache/dmoji/emojis.txt https://unicode.org/Public/emoji/14.0/emoji-test.txt
    cat ~/.cache/dmoji/emojis.txt | tail --lines=+35 | dmenu -l 10
}

icon() { cmd | awk '{print $5}' | tr -d '\n' | xclip -r -i -selection clipboard; }
number() { cmd | cut -d ' ' -f 1 | tr '\n' ';' | xclip -r -i -selection clipboard; }

help() {
    echo "Usage:	dmoji [option]

Options:
-i|--icon   │ Get the unicode icon (default)
-n|--number │ Get the unicode number
-c|--clear  │ Clear the cache
-h|--help   │ Print this help message and exit
"
}

parse_opts() {
    while [ $# -gt 0 ]; do
	case "$1" in
	    -h|--help)
		help=1
		shift
		;;
	    -i|--icon)
		icon=1
		shift
		;;
	    -n|--number)
		number=1
		shift
		;;
	    -c|--clear)
		clear=1
		shift
		;;
	esac
    done
}

main "$@"
