#!/bin/sh

cmd="$(wget -O- -q https://unicode.org/Public/emoji/14.0/emoji-test.txt | tail --lines=+35 | dmenu -l 10)"

icon() {
    printf "$cmd" | awk '{print $5}' | tr -d '\n' | xclip -r -i -selection clipboard
}

number() {
    printf "$cmd" | cut -d ' ' -f 1 | tr '\n' ';' | xclip -r -i -selection clipboard
}

if [ "$1" = "-n" -o "$1" = "--number" ]; then
    number
elif [ "$1" = "-i" -o "$1" = "--icon" ]; then
    icon
else
    icon
fi
